In [13]:
import numpy as np

# Laboratorio 1
## Practica utilizando NumPy.

### 1. Escriba una función usando NumPy para calcular la multiplicación de dos matrices dadas

In [14]:
def multiplicar_matrices(A, B):
    return np.matmul(A, B)

# probar la funcion
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[5, 6], [7, 8], [9, 10]])
print('A:\n', A)
print('B:\n', B)
print('multiplicacion AB:\n', multiplicar_matrices(A, B))

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[ 5  6]
 [ 7  8]
 [ 9 10]]
multiplicacion AB:
 [[ 46  52]
 [109 124]
 [172 196]]


### 2. Escriba una función usando NumPy para calcular el producto de dos vectores dados

In [15]:
def producto(A, B):
    return np.dot(A, B)

# probar la funcion
A = np.array([1, 2])
B = np.array([3, 4])
print('A:\n', A)
print('B:\n', B)
print('producto AB: ', producto(A, B))

A:
 [1 2]
B:
 [3 4]
producto AB:  11


### 3. Escriba una función usando NumPy para calcular el producto vectorial de dos vectores dados

In [16]:
def producto_vectorial(A, B):
    return np.cross(A, B)

# probar la funcion
A = np.array([1, 2])
B = np.array([3, 4])
print('A:\n', A)
print('B:\n', B)
print('producto AxB: ', producto_vectorial(A, B))

A:
 [1 2]
B:
 [3 4]
producto AxB:  -2


### 4. función usando NumPy para evaluar la convención de suma de Einstein de dos matrices multidimensionales dadas

In [17]:
def suma_einstein(A, B):
    return np.einsum('mk,kn', A, B)

# probar la funcion
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A:\n', A)
print('B:\n', B)
print('Suma de einstein:\n',suma_einstein(A, B))

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
Suma de einstein:
 [[19 22]
 [43 50]]


### 5. Escriba una función usando NumPy para calcular los valores propios y los vectores propios de una matriz cuadrada dada.

In [18]:
def valores_vectores_propios(A):
    return np.linalg.eig(A)


# probar la funcion
A = np.array([[1, 2], [3, 4]])
print('A:', A)

valores_propios, vectores_propios = valores_vectores_propios(A)
print('valores propios:\n', valores_propios)
print('vectores_propios:\n', vectores_propios)

A: [[1 2]
 [3 4]]
valores propios:
 [-0.37228132  5.37228132]
vectores_propios:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### 6. Escriba una función usando NumPy para calcular el determinante de una matriz

In [19]:
def determinante(A):
    return np.linalg.det(A)

# probar la funcion
A = np.array([[1, 2], [3, 4]])
print('A:\n', A)
print('determinante: ', determinante(A))

A:
 [[1 2]
 [3 4]]
determinante:  -2.0000000000000004


### 7. Escriba una función usando NumPy para calcular la inversa de una matriz dada

In [20]:
def inversa(A):
    return np.linalg.inv(A)

# probar la funcion
A = np.array([[1, 2], [3, 4]])
print('A:\n', A)
print('inversa: \n', inversa(A))

A:
 [[1 2]
 [3 4]]
inversa: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 8. Escriba una función usando NumPy para calcular la suma del elemento diagonal de una matriz dada.

In [21]:
def suma_diagonal(A):
    return np.trace(A)

# probar la funcion
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A:\n', A)
print('suma diagonal: ', suma_diagonal(A))


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
suma diagonal:  15
